create table REN_ANUNCIOS
(
    ID_ANUNCIO      NUMBER(5),
    NOMBRE_ANUNCIO  VARCHAR2(25),
    FECHA_CADUCIDAD DATE,
    PRECIO_ANUNCIO  NUMBER(5, 2),
    FORMATO         VARCHAR2(15),
    IMAGEN_ANUNCIO  VARCHAR2(75)
)
/

